cluster-config: 'profiles/wynton-qsub/cluster.yaml'
jobscript: 'profiles/wynton-qsub/jobscript.sh'
drmaa: " -cwd \
        -v PATH \
        -pe smp {cluster.processors} \
        -l mem_free={cluster.pmem}M \
        -l h_rt={cluster.walltime} \
        -o {cluster.outdir} \
        -j yes \
        -terse \
        "
jobs: 12
notemp: true
local-cores: 6
latency-wait: 60
max-jobs-per-second: 10
printshellcmds: true
keep-going: true
resources: 'nas_io_threads=60'
use-conda: true
use-singularity: true
config: 'MAX_THREADS=24'
jobname: '{name}.{jobid}.snakejob'
