cluster-config: 'profiles/wynton-qsub/cluster.yaml'
jobscript: 'profiles/wynton-qsub/jobscript.sh'
cluster: >-
    qsub -v PATH="$PATH" \
         -A {cluster.alloc} -q {cluster.queue} \
         -l nodes=1:ppn={cluster.ppn} -l pmem={cluster.pmem}mb \
         -l walltime={cluster.walltime} \
         -m {cluster.mail_options} \
         -o {cluster.stdout_file} -e {cluster.stderr_file}
notemp: true
timestamp: true
local-cores: 6
printshellcmds: true
keep-going: true
resources: 'net_requests_per_second=3'
use-conda: true
use-singularity: true
